name: first-workflow
on: [push]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    step:
      - name: echo Hello
        run: echo "Hello World"
      - name: multiple line command:
        run: |
         node -v  
         npm -v

